### ISSUE TITLE
Unknown logging category name

### ISSUE THREAD

**Issue by vsacheti** [eclipse-ee4j/eclipselink#620]
Hello, I am trying to use `slf4j Logger` with eclipse link and getting this issue. I see a bug ticket opened with it too, but its still Open. Can you please suggest any workaround to resolve this or fix this issue.

Here is the exception logs
```
Internal Exception: java.lang.IllegalArgumentException: Unknown logging category name.
        at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionLoadingFromUrl(PersistenceUnitLoadingException.java:100)
        at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceArchive(PersistenceUnitProcessor.java:622)
        at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getPersistenceUnits(PersistenceUnitProcessor.java:506)
        at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfoInArchive(JPAInitializer.java:179)
        at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfoInArchives(JPAInitializer.java:161)
        at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfo(JPAInitializer.java:142)
        at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:188)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
        at com.walmart.p13n.ccpa.db.service.GovernanceService.<init>(GovernanceService.java:42)
        at com.walmart.p13n.ccpa.KafkaReceiver.updateTicketStatus(KafkaReceiver.java:139)
        at com.walmart.p13n.ccpa.KafkaReceiver.lambda$runConsumer$0(KafkaReceiver.java:115)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.walmart.p13n.ccpa.KafkaReceiver.runConsumer(KafkaReceiver.java:85)
        at com.walmart.p13n.ccpa.KafkaReceiver.main(KafkaReceiver.java:259)
Caused by: java.lang.IllegalArgumentException: Unknown logging category name.
        at org.eclipse.persistence.logging.slf4j.SLF4JLogger.shouldLog(SLF4JLogger.java:244)
        at org.eclipse.persistence.internal.helper.XMLHelper.createParserFactory(XMLHelper.java:94)
        at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceXML(PersistenceUnitProcessor.java:631)
        at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceArchive(PersistenceUnitProcessor.java:620)
        ... 12 common frames omitted
```

Here are my dependencies
```
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <!-- needed for jpa slf4j Logger-->
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.extension</artifactId>
            <version>2.7.0</version>
        </dependency>
```
And I have added following line to my `persistence.xml`
```
<property name="eclipselink.logging.logger" value="org.eclipse.persistence.logging.slf4j.SLF4JLogger"/>
```

If you need any more information, please let me know.

Here is the related bug ticket: https://bugs.eclipse.org/bugs/show_bug.cgi?id=521424
It has listed a workaround using reflection technique, which I dont want to do.

**Comment by rfelcman** [comment]
I think, that this bug is fixed in 2.7.5 see PR #461 .
Could You please try update dependencies into:
```
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.7.5</version>
        </dependency>
        <dependency>
            <!-- needed for jpa slf4j Logger-->
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.extension</artifactId>
            <version>2.7.5</version>
        </dependency>
```

**Comment by rfelcman** [comment]
There is no any response for a last three months. I'm closing this bug now.

**Comment by pettired** [comment]
Hello,
We are using version 2.7.7 for eclipseLink & it's extension
 ```
<dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.7.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <!-- needed for jpa slf4j Logger-->
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>org.eclipse.persistence.extension</artifactId>
            <version>2.7.7</version>
        </dependency>
```

 & we still see this error:
```
 Internal Exception: java.lang.IllegalArgumentException: Unknown logging category name.
   at org.eclipse.persistence.exceptions.PersistenceUnitLoadingException.exceptionLoadingFromUrl(PersistenceUnitLoadingException.java:100)
   at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceArchive(PersistenceUnitProcessor.java:619)
   at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.getPersistenceUnits(PersistenceUnitProcessor.java:503)
   at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfoInArchive(JPAInitializer.java:178)
   at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfoInArchives(JPAInitializer.java:160)
   at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.findPersistenceUnitInfo(JPAInitializer.java:141)
   at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:188)
   at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
   at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
   ....
 Caused by: java.lang.IllegalArgumentException: Unknown logging category name.
  at org.eclipse.persistence.logging.slf4j.SLF4JLogger.shouldLog(SLF4JLogger.java:246)
   at org.eclipse.persistence.internal.helper.XMLHelper.createParserFactory(XMLHelper.java:94)
   at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceXML(PersistenceUnitProcessor.java:628)
   at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processPersistenceArchive(PersistenceUnitProcessor.java:617)
   ... 92 more
```

**Comment by pettired** [comment]
Do we have to set this property in _persistence.xml_ ? Because we are not doing it yet!
`<property name="eclipselink.logging.logger" value="org.eclipse.persistence.logging.slf4j.SLF4JLogger"/>`

**Comment by rfelcman** [comment]
Yes, please set this property if You want use SLF4J. If it's possible could You please provide there `persistence.xml` and `orm.xml` (or similar if exists). It seems, that there is something wrong in these files.

**Comment by pettired** [comment]
Ok. We actually don't need SLF4J or any logging with JPA.
So we are thinking to turn off JPA logging to get rid of this issue:
<property name="eclipselink.logging.level" value="OFF"/>

**Comment by dlsber** [comment]
Hi,
Looking at the above exception mentioned by pettired, we see that the exception is only thrown occasionally. It might be related to starting and stopping the application based on the comments in the [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521424) : "When i restart a PU (shut down EMF then start again) without stopping the JVM."

After checking the [changes ](https://github.com/eclipse-ee4j/eclipselink/pull/461/commits/ae84f658ecaecfc6f53630f6afd8e96be5835b8d) made to fix this bug I can confirm that LogCategory "MOXY" exists in the dependency, but the same exception is still thrown.

Logging is not configured in the persistence.xml file, it should be using default settings.

Do you know any pattern to reproduce the issue? The application runs in WebLogic Server Version: 12.2.1.3.0 .
How could we log the log category name that is supposed to be missing?

**Comment by rfelcman** [comment]
About 
_Do you know any pattern to reproduce the issue?
How could we log the log category name that is supposed to be missing?_
Sorry, but I have to answer **no** for booth questions. Only possible way how to get more details about this one is debug it.
But from _It might be related to starting and stopping the application based_ comment I see there another possible issue with class loading. Are You sure , that fixed EclipseLink (2.7.7) version is used. Maybe origin one from WLS server is used instead from application level. You can check possible class collisions by WLS-CAT (https://docs.oracle.com/cd/E24329_01/web.1211/e24368/classloading.htm#WLPRG495).
